# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.6
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Build
          command: npm run build
  unit-test:
    docker:
      - image: circleci/node:10.6
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Unit Tests
          command: npm t
  e2e-test:
    docker:
      - image: circleci/node:10.6
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Build
          command: npm run build
      - run:
          name: E2E Tests
          command: npm run e2e
  publish:
    docker:
      - image: circleci/node:10.6

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: NPMRC
          command: echo "registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
      - run:
          name: Set Git user info
          command: git config --global user.email "renaudin.yann@gmail.com"
      - run:
          name: Publish to NPM
          command: npm run publish

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - unit-test:
          requires:
            - build
      - e2e-test:
          requires:
            - build
      - publish:
          requires:
            - unit-test
            - e2e-test
          # filters:
          #   branches:
          #     only:
          #       - master
